### PR TITLE
updated bot to discord.js version 13

### PR DESCRIPTION
**Pull request by Ascynx**
updated to discordjs v13.xx.xx, which means it can now implement modals, interactions, buttons and other discordjs 13 features.
and limited discord.js imports to values used.

the use of schedule in bazaar.js was changed to use setInterval() which is a method directly implemented into nodejs.

the bot's readme.md was update to explain the changes to be able to merge an outside bot to the code.

### CODE REVIEW

**Review by IThundxr — APPROVED** [review]
should work havnt tested it locally yet

**Review by IThundxr — DISMISSED** [review]

**Review by symt — COMMENTED** [review]
Remove node-schedule from package.json since you're just using setInterval instead.

**Comment by IThundxr** [comment]
This is a good time to merge as discord api updated meaning v12 can't figure out new responses

**Comment by symt** [comment]
I'm popping this in 1.5.0 instead since that branch is about to be released. I'll do the documentation fixes and stuff after.

**Review by symt — APPROVED** [review]

**Pull request merged**
